[package]
name = "network_session_model"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
derive-new = "0.5.8"
derive_deref = "1.1.0"
game_input_model = { path = "../game_input_model" }
serde = { version = "1.0.105", features = ["derive"] }
structopt = "0.3.12"
