[package]
name = "network_mode_selection"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
derivative = "2.1.0"
derive-new = "0.5.8"
log = "0.4.8"
menu_model = { path = "../menu_model" }
network_mode_selection_model = { path = "../network_mode_selection_model" }
session_host = { path = "../session_host" }
session_join = { path = "../session_join" }
state_registry = { path = "../state_registry" }
