[package]
name = "map_play"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
map_model = { path = "../map_model" }
derive-new = "0.5.6"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[features]
nightly = ["amethyst/nightly"]
