[package]
name = "spawn_loading"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/kabergstrom/amethyst.git", features = ["no-slow-safety-checks", "vulkan", "experimental-assets"], branch = "new-asset-system" }
animation_support = { path = "../animation_support" }
application = { path = "../application" }
spawn_model = { path = "../spawn_model" }
derive-new = "0.5.8"
serde = "1.0.99"
shape_model = { path = "../shape_model" }
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/kabergstrom/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan", "experimental-assets"], branch = "new-asset-system" }
amethyst_test = { git = "https://github.com/kabergstrom/amethyst.git", branch = "new-asset-system" }

[features]
nightly = ["amethyst/nightly"]
