[package]
name = "character_play"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "test-support", "wav"] }
approx = "0.3.2"
asset_model = { path = "../asset_model" }
character_model = { path = "../character_model" }
charge_model = { path = "../charge_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
input_reaction_model = { path = "../input_reaction_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
mirrored_model = { path = "../mirrored_model" }
object_model = { path = "../object_model" }
sequence_model = { path = "../sequence_model" }
