[package]
name = "kinematic_loading"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_model = { path = "../asset_model" }
derive-new = "0.5.8"
kinematic_model = { path = "../kinematic_model" }
sequence_loading_spi = { path = "../sequence_loading_spi" }
serde = { version = "1.0.104", features = ["derive"] }
typename = "0.1.2"
typename_derive = "0.1.4"

[features]
nightly = ["amethyst/nightly"]
