[package]
name = "map_selection"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "test-support"] }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
asset_model = { path = "../asset_model" }
asset_selection_model = { path = "../asset_selection_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
log = "0.4.8"
map_selection_model = { path = "../map_selection_model" }
state_registry = { path = "../state_registry" }
