[package]
name = "map_selection_model"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_model = { path = "../asset_model" }
derivative = "1.0.3"
serde = { version = "1.0.102", features = ["derive"] }
structopt = "0.3.3"
structopt-derive = "0.3.3"

[features]
nightly = ["amethyst/nightly"]
