[package]
name = "state_play"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_menu = { path = "../application_menu" }
asset_model = { path = "../asset_model" }
camera_play = { path = "../camera_play" }
derivative = "1.0.3"
derive-new = "0.5.8"
log = "0.4.8"
shrev_support = { path = "../shrev_support" }
state_registry = { path = "../state_registry" }
state_support = { path = "../state_support" }
tracker = { path = "../tracker" }
typename = "0.1.1"
typename_derive = "0.1.3"
ui_label_play = { path = "../ui_label_play" }

[features]
nightly = ["amethyst/nightly"]
