[package]
name = "state_play"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
asset_model = { path = "../asset_model" }
camera_play = { path = "../camera_play" }
derivative = "2.1.0"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
log = "0.4.8"
shrev_support = { path = "../shrev_support" }
state_registry = { path = "../state_registry" }
state_support = { path = "../state_support" }
tracker = { path = "../tracker" }
ui_model_spi = { path = "../ui_model_spi" }
