[package]
name = "session_join"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "gl", "test-support"] }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
derivative = "2.1.0"
derive-new = "0.5.8"
log = "0.4.8"
network_session_model = { path = "../network_session_model" }
session_join_model = { path = "../session_join_model" }
session_lobby = { path = "../session_lobby" }
state_registry = { path = "../state_registry" }
