[package]
name = "game_mode_selection_stdio"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_event = { path = "../application_event" }
application_menu = { path = "../application_menu" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
derive-new = "0.5.6"
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2.18"
structopt-derive = "0.2.18"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
assets_test = { path = "../assets_test" }

[features]
nightly = ["amethyst/nightly"]
