[package]
name = "game_mode_selection_stdio"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
application_event = { path = "../application_event" }
menu_model = { path = "../menu_model" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
derive-new = "0.5.8"
stdio_spi = { path = "../stdio_spi" }
