[package]
name = "sprite_model"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_derive = { path = "../asset_derive" }
derive-new = "0.5.6"
derive_deref = "1.1.0"
sequence_model = { path = "../sequence_model" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.94"
specs-derive = "0.4.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
toml = "0.5.1"

[features]
nightly = ["amethyst/nightly"]
