[package]
name = "sprite_model"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.99.5"
kinematic_model = { path = "../kinematic_model" }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
sequence_model = { path = "../sequence_model" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.105", features = ["derive"] }
strum = "0.18.0"
strum_macros = "0.18.0"
