[package]
name = "input_reaction_play"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "gl", "test-support"] }
approx = "0.3.2"
asset_model = { path = "../asset_model" }
asset_selection_model = { path = "../asset_selection_model" }
asset_ui_model = { path = "../asset_ui_model" }
chase_model = { path = "../chase_model" }
control_settings_model = { path = "../control_settings_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
game_play_model = { path = "../game_play_model" }
input_reaction_model = { path = "../input_reaction_model" }
log = "0.4.8"
network_mode_selection_model = { path = "../network_mode_selection_model" }
network_session_model = { path = "../network_session_model" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
session_host_model = { path = "../session_host_model" }
session_join_model = { path = "../session_join_model" }
session_lobby_model = { path = "../session_lobby_model" }
state_registry = { path = "../state_registry" }
ui_form_model = { path = "../ui_form_model" }
ui_model = { path = "../ui_model" }
