[package]
name = "map_model"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
background_model = { path = "../background_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.99.2"
enumflags2 = "0.6.2"
logic_clock = { path = "../logic_clock" }
sequence_model = { path = "../sequence_model" }
serde = { version = "1.0.104", features = ["derive"] }
slotmap = "0.4.0"
sprite_model = { path = "../sprite_model" }
strum = "0.17.1"
strum_macros = "0.17.1"
typename = "0.1.2"
typename_derive = "0.1.4"

[features]
nightly = ["amethyst/nightly"]
