[package]
name = "game_input"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
asset_model = { path = "../asset_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
log = "0.4.8"
network_session_model = { path = "../network_session_model" }
serde = { version = "1.0.105", features = ["derive"] }
