[package]
name = "object_play"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
derivative = "2.1.0"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
kinematic_model = { path = "../kinematic_model" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
mirrored_model = { path = "../mirrored_model" }
object_model = { path = "../object_model" }
sequence_model = { path = "../sequence_model" }
