[package]
name = "object_play"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "vulkan"], branch = "maintenance/update-dependencies" }
derivative = "1.0.2"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
kinematic_model = { path = "../kinematic_model" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
object_model = { path = "../object_model" }
sequence_model = { path = "../sequence_model" }
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
amethyst_test = { git = "https://github.com/azriel91/amethyst.git", branch = "maintenance/update-dependencies" }
application_test_support = { path = "../application_test_support" }
approx = "0.3.2"
asset_model = { path = "../asset_model" }
map_loading = { path = "../map_loading" }
pretty_assertions = "0.6.1"

[features]
nightly = ["amethyst/nightly"]
