[package]
name = "energy_prefab"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
energy_loading = { path = "../energy_loading" }
energy_model = { path = "../energy_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
log = "0.4.6"
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
object_prefab = { path = "../object_prefab" }
shred = "0.7.0"
shred-derive = "0.5.1"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
pretty_assertions = "0.6.1"
sequence_loading = { path = "../sequence_loading" }
sequence_model = { path = "../sequence_model" }

[features]
nightly = ["amethyst/nightly"]
