[package]
name = "stdio_spi"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "vulkan"], branch = "maintenance/update-dependencies" }
application_event = { path = "../application_event" }
clap = "2.33.0"
derive-new = "0.5.8"
err-derive = "0.1.5"
log = "0.4.8"
structopt = "0.2.18"
typename = "0.1.1"
typename_derive = "0.1.3"

[features]
nightly = ["amethyst/nightly"]
