[package]
name = "sequence_model"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
bimap = "0.4.0"
derivative = "1.0.2"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.15.1-pre"
fnv = "1.0.6"
game_input_model = { path = "../game_input_model" }
logic_clock = { path = "../logic_clock" }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
sequence_model_core = { path = "../sequence_model_core" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.99"
slotmap = { version = "0.4.0", features = ["serde"] }
specs-derive = "0.4.0"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[features]
nightly = ["amethyst/nightly"]
