[package]
name = "sequence_model"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
bimap = "0.4.0"
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.99.2"
indexmap = { version = "1.3.0", features = ["serde-1"] }
logic_clock = { path = "../logic_clock" }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
sequence_model_core = { path = "../sequence_model_core" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.104", features = ["derive"] }
slotmap = { version = "0.4.0", features = ["serde"] }
strum = "0.17.1"
strum_macros = "0.17.1"
typename = "0.1.2"
typename_derive = "0.1.4"

[features]
nightly = ["amethyst/nightly"]
