[package]
name = "game_mode_selection_ui"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_menu = { path = "../application_menu" }
application_ui = { path = "../application_ui" }
derivative = "1.0.2"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
heck = "0.3.1"
log = "0.4.8"
shred = "0.9.2"
shred-derive = "0.6.1"
specs-derive = "0.4.0"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"
ui_audio_model = { path = "../../crate/ui_audio_model" }

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_test_support = { path = "../application_test_support" }

[features]
nightly = ["amethyst/nightly"]
