[package]
name = "game_mode_selection_ui"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_menu = { path = "../application_menu" }
application_ui = { path = "../application_ui" }
asset_model = { path = "../asset_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
sequence_model = { path = "../sequence_model" }
shrev_support = { path = "../shrev_support" }
sprite_model = { path = "../sprite_model" }
state_registry = { path = "../state_registry" }
state_support = { path = "../state_support" }
strum = "0.16.0"
strum_macros = "0.16.0"
typename = "0.1.1"
typename_derive = "0.1.3"
ui_audio_model = { path = "../../crate/ui_audio_model" }
ui_menu_item_model = { path = "../ui_menu_item_model" }

[features]
nightly = ["amethyst/nightly"]
