[package]
name = "network_input_play"
version = "0.19.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "test-support", "wav", "web_socket"] }
derivative = "2.1.1"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
log = "0.4.11"
net_model = { path = "../net_model" }
network_session_model = { path = "../network_session_model" }
structopt = "0.3.18"
