[package]
name = "game_play_hud"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
asset_gfx_gen = { path = "../asset_gfx_gen" }
charge_model = { path = "../charge_model" }
chase_model = { path = "../chase_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
object_model = { path = "../object_model" }
parent_model = { path = "../parent_model"}
