[package]
name = "object_loading"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_model = { path = "../asset_model" }
audio_loading = { path = "../audio_loading" }
audio_model = { path = "../audio_model" }
character_model = { path = "../character_model" }
collision_model = { path = "../collision_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
energy_model = { path = "../energy_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
object_model = { path = "../object_model" }
object_type = { path = "../object_type" }
rayon = "1.3.0"
sequence_model = { path = "../sequence_model" }
serde = { version = "1.0.104", features = ["derive"] }
spawn_model = { path = "../spawn_model" }
sprite_model = { path = "../sprite_model" }
typename = "0.1.2"
typename_derive = "0.1.4"

[features]
nightly = ["amethyst/nightly"]
