[package]
name = "stdio_command_stdio"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "gl", "test-support"] }
application_event = { path = "../application_event" }
derive-new = "0.5.8"
log = "0.4.8"
stdio_command_model = { path = "../stdio_command_model" }
stdio_input = { path = "../stdio_input" }
stdio_spi = { path = "../stdio_spi" }
