[package]
name = "sequence_model_derive"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
proc_macro_roids = "0.4.0"
quote = "1.0.2"
syn = { version = "1.0.3", features = ["extra-traits", "visit"] }

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["test-support", "vulkan"]}
asset_derive = { path = "../asset_derive" }
derivative = "1.0.2"
derive_deref = "1.1.0"
sequence_model_core = { path = "../sequence_model_core" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.99"
specs-derive = "0.4.0"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"
