[package]
name = "sequence_model_derive"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true
doctest = true
test = false

[dependencies]
proc-macro2 = "1.0.7"
proc_macro_roids = "0.6.0"
quote = "1.0.2"
syn = { version = "1.0.13", features = ["extra-traits", "visit"] }

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
asset_derive = { path = "../asset_derive" }
derivative = "1.0.3"
derive_deref = "1.1.0"
sequence_model_core = { path = "../sequence_model_core" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.104", features = ["derive"] }
strum = "0.17.1"
strum_macros = "0.17.1"
typename = "0.1.2"
typename_derive = "0.1.4"
