[package]
name = "sequence_model_derive"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true
doctest = true
test = false

[dependencies]
proc-macro2 = "1.0.10"
proc_macro_roids = "0.7.0"
quote = "1.0.3"
syn = { version = "1.0.17", features = ["extra-traits", "visit"] }

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
asset_derive = { path = "../asset_derive" }
derivative = "2.1.0"
derive_deref = "1.1.0"
sequence_model_core = { path = "../sequence_model_core" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.105", features = ["derive"] }
strum = "0.18.0"
strum_macros = "0.18.0"
