[package]
name = "game_mode_selection_model"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_menu = { path = "../application_menu" }
serde = { version = "1.0.104", features = ["derive"] }
structopt = "0.3.7"
structopt-derive = "0.4.0"
strum = "0.17.1"
strum_macros = "0.17.1"
typename = "0.1.2"
typename_derive = "0.1.4"

[features]
nightly = ["amethyst/nightly"]
