[package]
name = "asset_model"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
bimap = "0.4.0"
derivative = "1.0.2"
derive-new = "0.5.8"
derive_builder = "0.8.0"
derive_deref = "1.1.0"
derive_more = "0.15.1-pre"
indexmap = { version = "1.1.0", features = ["serde-1"] }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
object_type = { path = "../object_type" }
serde = "1.0.99"
slotmap = { version = "0.4.0", features = ["serde"] }
strum = "0.15.0"
strum_macros = "0.15.0"

[dev-dependencies]
tempfile = "3.1.0"

[features]
nightly = ["amethyst/nightly"]
