[package]
name = "collision_audio_loading"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_loading = { path = "../asset_loading" }
collision_audio_model = { path = "../collision_audio_model" }
derivative = "1.0.2"
derive-new = "0.5.8"
log = "0.4.8"
shred = "0.9.2"
shred-derive = "0.6.1"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }

[features]
nightly = ["amethyst/nightly"]
