[package]
name = "charge_model"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
derivative = "1.0.2"
derive-new = "0.5.6"
derive_deref = "1.1.0"
derive_more = "0.15.0"
logic_clock = { path = "../logic_clock" }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
serde = "1.0.94"
specs-derive = "0.4.0"

[features]
nightly = ["amethyst/nightly"]
