[package]
name = "charge_model"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.15.1-pre"
logic_clock = { path = "../logic_clock" }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
serde = "1.0.101"

[features]
nightly = ["amethyst/nightly"]
