[package]
name = "spawn_play"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "vulkan"], branch = "maintenance/update-dependencies" }
asset_model = { path = "../asset_model" }
character_model = { path = "../character_model" }
character_prefab = { path = "../character_prefab" }
derivative = "1.0.2"
derive-new = "0.5.8"
energy_model = { path = "../energy_model" }
energy_prefab = { path = "../energy_prefab" }
game_model = { path = "../game_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
object_model = { path = "../object_model" }
object_prefab = { path = "../object_prefab" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
spawn_model = { path = "../spawn_model" }
team_model = { path = "../team_model" }
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
application_test_support = { path = "../application_test_support" }
asset_model = { path = "../asset_model" }
assets_test = { path = "../assets_test" }
energy_loading = { path = "../energy_loading" }
loading = { path = "../loading" }
pretty_assertions = "0.6.1"

[features]
nightly = ["amethyst/nightly"]
