[package]
name = "character_prefab"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_model = { path = "../asset_model" }
character_model = { path = "../character_model" }
charge_model = { path = "../charge_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
log = "0.4.8"
map_model = { path = "../map_model" }
object_model = { path = "../object_model" }
object_status_model = { path = "../object_status_model" }
sequence_model = { path = "../sequence_model" }
typename = "0.1.2"
typename_derive = "0.1.4"

[features]
nightly = ["amethyst/nightly"]
