[package]
name = "character_prefab"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/kabergstrom/amethyst.git", features = ["no-slow-safety-checks", "vulkan", "experimental-assets"], branch = "new-asset-system" }
character_loading = { path = "../character_loading" }
character_model = { path = "../character_model" }
charge_model = { path = "../charge_model" }
derivative = "1.0.2"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
log = "0.4.8"
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
object_prefab = { path = "../object_prefab" }
object_status_model = { path = "../object_status_model" }
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/kabergstrom/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan", "experimental-assets"], branch = "new-asset-system" }
amethyst_test = { git = "https://github.com/kabergstrom/amethyst.git", branch = "new-asset-system" }
game_input_model = { path = "../game_input_model" }
indexmap = { version = "1.1.0", features = ["serde-1"] }
pretty_assertions = "0.6.1"
sequence_loading = { path = "../sequence_loading" }
sequence_model = { path = "../sequence_model" }

[features]
nightly = ["amethyst/nightly"]
