[package]
name = "object_model"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
derive_deref = "1.1.0"
derive_more = "0.15.0"
logic_clock = { path = "../logic_clock" }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
object_model_derive = { path = "../object_model_derive" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.94"
shape_model = { path = "../shape_model" }
spawn_model = { path = "../spawn_model" }
specs-derive = "0.4.0"
sprite_loading = { path = "../sprite_loading" }
sprite_model = { path = "../sprite_model" }
strum = "0.15.0"
strum_macros = "0.15.0"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
kinematic_model = { path = "../kinematic_model" }
object_status_model = { path = "../object_status_model" }
object_type = { path = "../object_type", features = ["test-support"] }
pretty_assertions = "0.6.1"
toml = "0.5.1"
typename = "0.1.1"
typename_derive = "0.1.3"

[features]
nightly = ["amethyst/nightly"]
