[package]
name = "object_model"
version = "0.19.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "test-support", "wav", "web_socket"] }
asset_model = { path = "../asset_model" }
audio_model = { path = "../audio_model" }
collision_model = { path = "../collision_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.99.5"
indexmap = { version = "1.3.2", features = ["serde-1"] }
kinematic_model = { path = "../kinematic_model" }
logic_clock = { path = "../logic_clock" }
numeric_newtype_derive = { path = "../numeric_newtype_derive" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.105", features = ["derive"] }
shape_model = { path = "../shape_model" }
spawn_model = { path = "../spawn_model" }
sprite_model = { path = "../sprite_model" }
strum = "0.18.0"
strum_macros = "0.18.0"
