[package]
name = "game_mode_selection"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
application_event = { path = "../application_event" }
menu_model = { path = "../menu_model" }
application_state = { path = "../application_state" }
character_selection = { path = "../character_selection" }
control_settings = { path = "../control_settings" }
derivative = "2.1.0"
derive-new = "0.5.8"
game_loading = { path = "../game_loading" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
game_play = { path = "../game_play" }
log = "0.4.8"
map_selection = { path = "../map_selection" }
network_mode_selection = { path = "../network_mode_selection" }
state_registry = { path = "../state_registry" }
