[package]
name = "energy_model"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "vulkan"], branch = "maintenance/update-dependencies" }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
audio_model = { path = "../audio_model" }
collision_model = { path = "../collision_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.15.0"
kinematic_model = { path = "../kinematic_model" }
object_model = { path = "../object_model" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.101"
spawn_model = { path = "../spawn_model" }
slotmap = { version = "0.4.0", features = ["serde"] }
sprite_model = { path = "../sprite_model" }
strum = "0.16.0"
strum_macros = "0.16.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
indexmap = { version = "1.2.0", features = ["serde-1"] }
pretty_assertions = "0.6.1"
serde_yaml = "0.8.9"
shape_model = { path = "../shape_model" }

[features]
nightly = ["amethyst/nightly"]
