[package]
name = "energy_model"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/kabergstrom/amethyst.git", features = ["no-slow-safety-checks", "vulkan", "experimental-assets"], branch = "new-asset-system" }
asset_derive = { path = "../asset_derive" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.15.0"
object_model = { path = "../object_model" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.99"
spawn_model = { path = "../spawn_model" }
specs-derive = "0.4.0"
sprite_model = { path = "../sprite_model" }
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
pretty_assertions = "0.6.1"
serde_yaml = "0.8.9"
shape_model = { path = "../shape_model" }

[features]
nightly = ["amethyst/nightly"]
