[package]
name = "character_model"
version = "0.15.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
approx = "0.3.2"
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
audio_model = { path = "../audio_model" }
charge_model = { path = "../charge_model" }
collision_model = { path = "../collision_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.15.0"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
kinematic_model = { path = "../kinematic_model" }
object_model = { path = "../object_model" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.102", features = ["derive"] }
slotmap = { version = "0.4.0", features = ["serde"] }
spawn_model = { path = "../spawn_model" }
sprite_model = { path = "../sprite_model" }
strum = "0.16.0"
strum_macros = "0.16.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[features]
nightly = ["amethyst/nightly"]
