[package]
name = "workspace_tests"
version = "0.17.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan", "test-support"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git", branch = "maintenance/correct-amethyst-test-features", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "vulkan"] }
application = { path = "../application" }
application_event = { path = "../application_event" }
application_input = { path = "../application_input" }
application_menu = { path = "../application_menu" }
application_robot = { path = "../application_robot" }
application_state = { path = "../application_state" }
application_test_support = { path = "../application_test_support" }
application_ui = { path = "../application_ui" }
approx = "0.3.2"
assert_cmd = "0.12.0"
asset_derive = { path = "../asset_derive" }
asset_gfx_gen = { path = "../asset_gfx_gen" }
asset_loading = { path = "../asset_loading" }
asset_model = { path = "../asset_model" }
asset_play = { path = "../asset_play" }
asset_selection_model = { path = "../asset_selection_model" }
asset_selection_stdio = { path = "../asset_selection_stdio" }
asset_selection_ui_play = { path = "../asset_selection_ui_play" }
asset_ui_model = { path = "../asset_ui_model" }
assets_test = { path = "../assets_test" }
audio_loading = { path = "../audio_loading" }
audio_model = { path = "../audio_model" }
audio_play = { path = "../audio_play" }
background_loading = { path = "../background_loading" }
background_model = { path = "../background_model" }
bincode = "1.2.1"
bytes = "0.5.4"
camera_model = { path = "../camera_model" }
camera_play = { path = "../camera_play" }
character_loading = { path = "../character_loading" }
character_model = { path = "../character_model" }
character_play = { path = "../character_play" }
character_prefab = { path = "../character_prefab" }
character_selection = { path = "../character_selection" }
character_selection_model = { path = "../character_selection_model" }
character_selection_ui_model = { path = "../character_selection_ui_model" }
charge_model = { path = "../charge_model" }
charge_play = { path = "../charge_play" }
chase_model = { path = "../chase_model" }
chase_play = { path = "../chase_play" }
collision_audio_loading = { path = "../collision_audio_loading" }
collision_audio_model = { path = "../collision_audio_model" }
collision_audio_play = { path = "../collision_audio_play" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
collision_play = { path = "../collision_play" }
debug_util_amethyst = { path = "../debug_util_amethyst" }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
energy_loading = { path = "../energy_loading" }
energy_model = { path = "../energy_model" }
energy_prefab = { path = "../energy_prefab" }
enumflags2 = "0.6.2"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
game_input_stdio = { path = "../game_input_stdio" }
game_loading = { path = "../game_loading" }
game_mode_selection = { path = "../game_mode_selection" }
game_mode_selection_model = { path = "../game_mode_selection_model" }
game_mode_selection_stdio = { path = "../game_mode_selection_stdio" }
game_mode_selection_ui = { path = "../game_mode_selection_ui" }
game_model = { path = "../game_model" }
game_play = { path = "../game_play" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
game_play_stdio = { path = "../game_play_stdio" }
game_stats_model = { path = "../game_stats_model" }
hamcrest = "0.1.5"
indexmap = { version = "1.3.2", features = ["serde-1"] }
input_reaction_loading = { path = "../input_reaction_loading" }
input_reaction_model = { path = "../input_reaction_model" }
input_reaction_play = { path = "../input_reaction_play" }
kinematic_loading = { path = "../kinematic_loading" }
kinematic_model = { path = "../kinematic_model" }
lazy_static = "1.4.0"
loading = { path = "../loading" }
loading_model = { path = "../loading_model" }
log = "0.4.8"
logic_clock = { path = "../logic_clock" }
map_loading = { path = "../map_loading" }
map_model = { path = "../map_model" }
map_play = { path = "../map_play" }
map_selection = { path = "../map_selection" }
map_selection_model = { path = "../map_selection_model" }
map_selection_ui_model = { path = "../map_selection_ui_model" }
menu_model = { path = "../menu_model" }
mirrored_model = { path = "../mirrored_model" }
session_join_model = { path = "../session_join_model" }
session_join_play = { path = "../session_join_play" }
session_join_stdio = { path = "../session_join_stdio" }
network_mode_selection_model = { path = "../network_mode_selection_model" }
network_mode_selection_stdio = { path = "../network_mode_selection_stdio" }
network_session_model = { path = "../network_session_model" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }
object_status_model = { path = "../object_status_model" }
object_status_play = { path = "../object_status_play" }
object_type = { path = "../object_type" }
parent_model = { path = "../parent_model" }
parent_play = { path = "../parent_play" }
pretty_assertions = "0.6.1"
rayon = "1.3.0"
ron = "0.5.1"
sequence_loading = { path = "../sequence_loading" }
sequence_model = { path = "../sequence_model" }
sequence_play = { path = "../sequence_play" }
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
shape_model = { path = "../shape_model" }
slotmap = { version = "0.4.0", features = ["serde"] }
spawn_loading = { path = "../spawn_loading" }
spawn_model = { path = "../spawn_model" }
spawn_play = { path = "../spawn_play" }
sprite_loading = { path = "../sprite_loading" }
sprite_model = { path = "../sprite_model" }
sprite_play = { path = "../sprite_play" }
state_play = { path = "../state_play" }
state_registry = { path = "../state_registry" }
stdio_command_model = { path = "../stdio_command_model" }
stdio_command_stdio = { path = "../stdio_command_stdio" }
stdio_input = { path = "../stdio_input" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.3.9"
structopt-derive = "0.4.2"
strum = "0.17.1"
strum_macros = "0.17.1"
team_model = { path = "../team_model" }
tempfile = "3.1.0"
test_object_model = { path = "../test_object_model" }
test_support = { path = "../test_support" }
tracker = { path = "../tracker" }
ui_audio_loading = { path = "../ui_audio_loading" }
ui_audio_model = { path = "../ui_audio_model" }
ui_button_model = { path = "../ui_button_model" }
ui_form_model = { path = "../ui_form_model" }
ui_label_model = { path = "../ui_label_model" }
ui_loading = { path = "../ui_loading" }
ui_menu_item_model = { path = "../ui_menu_item_model" }
ui_model= { path = "../ui_model" }
ui_model_spi = { path = "../ui_model_spi" }
ui_play = { path = "../ui_play" }
