[package]
name = "input_reaction_model"
version = "0.17.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
approx = "0.3.2"
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
asset_selection_model = { path = "../asset_selection_model" }
control_settings_model = { path ="../control_settings_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
derive_deref = "1.1.0"
derive_more = "0.99.2"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
game_mode_selection_model = { path ="../game_mode_selection_model" }
game_play_model = { path ="../game_play_model" }
mirrored_model = { path ="../mirrored_model" }
network_mode_selection_model = { path ="../network_mode_selection_model" }
sequence_model = { path = "../sequence_model" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.104", features = ["derive"] }
smallvec = "1.2.0"

[features]
nightly = ["amethyst/nightly"]
