[package]
name = "application_ui"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "vulkan"], branch = "maintenance/update-dependencies" }
application = { path = "../application" }
application_robot = { path = "../application_robot" }
derive-new = "0.5.8"
serde = "1.0.101"
strum = "0.16.0"
strum_macros = "0.16.0"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
amethyst_test = { git = "https://github.com/azriel91/amethyst.git", branch = "maintenance/update-dependencies" }
assert_cmd = "0.11.1"
escargot = "0.5.0"
log = "0.4.8"
ron = "0.5.1"
structopt = "0.3.2"
structopt-derive = "0.3.2"

[features]
nightly = ["amethyst/nightly"]
