[package]
name = "application_ui"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application = { path = "../application" }
application_robot = { path = "../application_robot" }
derive-new = "0.5.6"
serde = "1.0.94"
strum = "0.15.0"
strum_macros = "0.15.0"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
assert_cmd = "0.11.1"
escargot = "0.5.0"
log = "0.4.6"
ron = "0.5.1"
structopt = "0.2.18"
structopt-derive = "0.2.18"

[features]
nightly = ["amethyst/nightly"]

[[example]]
name = "01_draw_text"
path = "examples/01_draw_text/main.rs"
