[package]
name = "application_menu"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
derivative = "1.0.2"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
log = "0.4.8"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
application_robot = { path = "../application_robot" }
application_ui = { path = "../application_ui" }
assert_cmd = "0.11.1"
escargot = "0.5.0"
rayon = "1.1.0"
structopt = "0.2.18"
structopt-derive = "0.2.18"

[features]
nightly = ["amethyst/nightly"]

[[example]]
name = "01_menu"
path = "examples/01_menu/main.rs"
