[package]
name = "control_settings"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_event = { path = "../application_event" }
derivative = "1.0.3"
derive-new = "0.5.8"
control_settings_model = { path = "../control_settings_model" }
log = "0.4.8"
state_registry = { path = "../state_registry" }

[features]
nightly = ["amethyst/nightly"]
