[package]
name = "game_loading"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "vulkan"], branch = "maintenance/update-dependencies" }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
asset_model = { path = "../asset_model" }
camera_model = { path = "../camera_model" }
character_model = { path = "../character_model" }
character_prefab = { path = "../character_prefab" }
character_selection_model = { path = "../character_selection_model" }
collision_model = { path = "../collision_model" }
derivative = "1.0.2"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
logic_clock = { path = "../logic_clock" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
num-traits = "0.2.8"
object_loading = { path = "../object_loading" }
object_prefab = { path = "../object_prefab" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
sequence_model_spi = { path = "../sequence_model_spi" }
sprite_model = { path = "../sprite_model" }
state_registry = { path = "../state_registry" }
team_model = { path = "../team_model" }
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
amethyst_test = { git = "https://github.com/azriel91/amethyst.git", branch = "maintenance/update-dependencies" }
asset_loading = { path = "../asset_loading" }
assets_test = { path = "../assets_test" }
audio_loading = { path = "../audio_loading" }
character_loading = { path = "../character_loading" }
collision_audio_loading = { path = "../collision_audio_loading" }
collision_loading = { path = "../collision_loading" }
energy_loading = { path = "../energy_loading" }
game_input_model = { path = "../game_input_model" }
kinematic_loading = { path = "../kinematic_loading" }
loading = { path = "../loading" }
loading_model = { path = "../loading_model" }
map_loading = { path = "../map_loading" }
map_selection = { path = "../map_selection" }
sequence_loading = { path = "../sequence_loading" }
spawn_loading = { path = "../spawn_loading" }
sprite_loading = { path = "../sprite_loading" }
ui_audio_loading = { path = "../../crate/ui_audio_loading" }

[features]
nightly = ["amethyst/nightly"]
