[package]
name = "game_loading"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
asset_model = { path = "../asset_model" }
background_model = { path = "../background_model" }
camera_model = { path = "../camera_model" }
character_model = { path = "../character_model" }
character_prefab = { path = "../character_prefab" }
character_selection_model = { path = "../character_selection_model" }
collision_model = { path = "../collision_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
logic_clock = { path = "../logic_clock" }
map_model = { path = "../map_model" }
map_selection_model = { path = "../map_selection_model" }
num-traits = "0.2.8"
object_prefab = { path = "../object_prefab" }
object_type = { path = "../object_type" }
sequence_model = { path = "../sequence_model" }
sequence_model_spi = { path = "../sequence_model_spi" }
sprite_model = { path = "../sprite_model" }
state_registry = { path = "../state_registry" }
team_model = { path = "../team_model" }
typename = "0.1.1"
typename_derive = "0.1.3"

[features]
nightly = ["amethyst/nightly"]
