[package]
name = "game_loading"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "test-support"] }
application_event = { path = "../application_event" }
application_state = { path = "../application_state" }
asset_model = { path = "../asset_model" }
camera_model = { path = "../camera_model" }
character_prefab = { path = "../character_prefab" }
character_selection_model = { path = "../character_selection_model" }
derivative = "2.1.0"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
game_model = { path = "../game_model" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
kinematic_model = { path = "../kinematic_model" }
map_model = { path = "../map_model" }
map_play = { path = "../map_play" }
map_selection_model = { path = "../map_selection_model" }
object_type = { path = "../object_type" }
state_registry = { path = "../state_registry" }
team_model = { path = "../team_model" }
