[package]
name = "object_test"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application_event = { path = "../application_event" }
collision_loading = { path = "../collision_loading" }
collision_model = { path = "../collision_model" }
derive-new = "0.5.6"
game_input_model = { path = "../game_input_model" }
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
sequence_loading = { path = "../sequence_loading" }
sequence_model = { path = "../sequence_model" }
spawn_loading = { path = "../spawn_loading" }
spawn_model = { path = "../spawn_model" }
sprite_loading = { path = "../sprite_loading" }
sprite_model = { path = "../sprite_model" }

[features]
nightly = ["amethyst/nightly"]
