[package]
name = "asset_gfx_gen"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
derivative = "1.0.2"
integer-sqrt = "0.1.2"
shred = "0.9.2"
shred-derive = "0.6.1"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
approx = "0.3.2"
derive-new = "0.5.8"
pretty_assertions = "0.6.1"

[features]
nightly = ["amethyst/nightly"]
