[package]
name = "map_selection_stdio"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_event = { path = "../application_event" }
asset_model = { path = "../asset_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
map_selection_model = { path = "../map_selection_model" }
stdio_spi = { path = "../stdio_spi" }
typename = "0.1.2"
typename_derive = "0.1.4"

[features]
nightly = ["amethyst/nightly"]
