[package]
name = "spawn_model"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
derive-new = "0.5.8"
derive_deref = "1.1.0"
kinematic_model = { path = "../kinematic_model" }
sequence_model = { path = "../sequence_model" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = "1.0.99"
slotmap = "0.4.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
serde_yaml = "0.8.9"

[features]
nightly = ["amethyst/nightly"]
