[package]
name = "spawn_model"
version = "0.19.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "test-support", "wav", "web_socket"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
derive-new = "0.5.8"
derive_deref = "1.1.0"
kinematic_model = { path = "../kinematic_model" }
sequence_model = { path = "../sequence_model" }
sequence_model_derive = { path = "../sequence_model_derive" }
sequence_model_spi = { path = "../sequence_model_spi" }
serde = { version = "1.0.106", features = ["derive"] }
