[package]
name = "game_input_stdio"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "vulkan"], branch = "maintenance/update-dependencies" }
application_event = { path = "../application_event" }
derive-new = "0.5.8"
game_input = { path = "../game_input" }
game_input_model = { path = "../game_input_model" }
stdio_spi = { path = "../stdio_spi" }
structopt = "0.2.18"
structopt-derive = "0.2.18"
strum = "0.15.0"
strum_macros = "0.15.0"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/azriel91/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"], branch = "maintenance/update-dependencies" }
amethyst_test = { git = "https://github.com/azriel91/amethyst.git", branch = "maintenance/update-dependencies" }
application_test_support = { path = "../application_test_support" }

[features]
nightly = ["amethyst/nightly"]
