[package]
name = "energy_play"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
collision_model = { path = "../collision_model" }
energy_model = { path = "../energy_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
shred = "0.7.0"
shred-derive = "0.5.1"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
shape_model = { path = "../shape_model" }

[features]
nightly = ["amethyst/nightly"]
