[package]
name = "ui_play"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
camera_model = { path = "../camera_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
sequence_model = { path = "../sequence_model" }
ui_model_spi = { path = "../ui_model_spi" }
