[package]
name = "input_reaction_loading"
version = "0.16.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
derivative = "1.0.3"
game_input_model = { path = "../game_input_model" }
input_reaction_model = { path = "../input_reaction_model" }
sequence_model = { path = "../sequence_model" }
typename = "0.1.1"

[features]
nightly = ["amethyst/nightly"]
