[package]
name = "game_play"
version = "0.14.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application_event = { path = "../application_event" }
asset_model = { path = "../asset_model" }
audio_model = { path = "../audio_model" }
audio_play = { path = "../audio_play" }
camera_model = { path = "../camera_model" }
camera_play = { path = "../camera_play" }
character_model = { path = "../character_model" }
character_play = { path = "../character_play" }
character_selection = { path = "../character_selection" }
charge_play = { path = "../charge_play" }
chase_play = { path = "../chase_play" }
collision_audio_play = { path = "../collision_audio_play" }
collision_model = { path = "../collision_model" }
collision_play = { path = "../collision_play" }
derivative = "1.0.3"
derive-new = "0.5.8"
energy_model = { path = "../energy_model" }
game_input = { path = "../game_input" }
game_model = { path = "../game_model" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
logic_clock = { path = "../logic_clock" }
map_model = { path = "../map_model" }
map_play = { path = "../map_play" }
map_selection_model = { path = "../map_selection_model" }
named_type = "0.2.1"
named_type_derive = "0.2.1"
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }
object_prefab = { path = "../object_prefab" }
object_status_model = { path = "../object_status_model" }
object_status_play = { path = "../object_status_play" }
sequence_model = { path = "../sequence_model" }
sequence_play = { path = "../sequence_play" }
shape_model = { path = "../shape_model" }
spawn_model = { path = "../spawn_model" }
spawn_play = { path = "../spawn_play" }
sprite_model = { path = "../sprite_model" }
state_registry = { path = "../state_registry" }
team_model = { path = "../team_model" }
tracker = { path = "../tracker" }
typename = "0.1.1"
typename_derive = "0.1.3"

[features]
nightly = ["amethyst/nightly"]
