[package]
name = "game_play"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "wasm", default-features = false, features = ["audio", "network", "renderer", "no-slow-safety-checks", "test-support", "wav"] }
application_event = { path = "../application_event" }
application_ui = { path = "../application_ui" }
asset_model = { path = "../asset_model" }
audio_model = { path = "../audio_model" }
audio_play = { path = "../audio_play" }
camera_model = { path = "../camera_model" }
camera_play = { path = "../camera_play" }
character_model = { path = "../character_model" }
character_play = { path = "../character_play" }
charge_play = { path = "../charge_play" }
chase_play = { path = "../chase_play" }
collision_audio_play = { path = "../collision_audio_play" }
collision_model = { path = "../collision_model" }
collision_play = { path = "../collision_play" }
derivative = "2.1.0"
derive-new = "0.5.8"
game_input_model = { path = "../game_input_model" }
game_model = { path = "../game_model" }
game_play_hud = { path = "../game_play_hud" }
game_play_model = { path = "../game_play_model" }
game_stats_model = { path = "../game_stats_model" }
input_reaction_model = { path = "../input_reaction_model" }
input_reaction_play = { path = "../input_reaction_play" }
kinematic_model = { path = "../kinematic_model" }
log = "0.4.8"
logic_clock = { path = "../logic_clock" }
map_model = { path = "../map_model" }
map_play = { path = "../map_play" }
map_selection_model = { path = "../map_selection_model" }
mirrored_model = { path = "../mirrored_model" }
object_model = { path = "../object_model" }
object_play = { path = "../object_play" }
object_status_model = { path = "../object_status_model" }
object_status_play = { path = "../object_status_play" }
sequence_model = { path = "../sequence_model" }
sequence_play = { path = "../sequence_play" }
shape_model = { path = "../shape_model" }
spawn_model = { path = "../spawn_model" }
spawn_play = { path = "../spawn_play" }
sprite_model = { path = "../sprite_model" }
sprite_play = { path = "../sprite_play" }
state_registry = { path = "../state_registry" }
state_support = { path = "../state_support" }
team_model = { path = "../team_model" }
tracker = { path = "../tracker" }
