[package]
name = "asset_loading"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/kabergstrom/amethyst.git", features = ["no-slow-safety-checks", "vulkan", "experimental-assets"], branch = "new-asset-system" }
application = { path = "../application" }
asset_model = { path = "../asset_model" }
derive-new = "0.5.8"
heck = "0.3.1"
itertools = "0.8.0"
log = "0.4.8"
map_model = { path = "../map_model" }
object_type = { path = "../object_type" }
serde = "1.0.99"
serde_yaml = "0.8.9"
strum = "0.15.0"

[dev-dependencies]
amethyst = { git = "https://github.com/kabergstrom/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan", "experimental-assets"], branch = "new-asset-system" }
amethyst_test = { git = "https://github.com/kabergstrom/amethyst.git", branch = "new-asset-system" }
derive_deref = "1.1.0"
hamcrest = "0.1.5"
pretty_assertions = "0.6.1"
tempfile = "3.1.0"

[features]
nightly = ["amethyst/nightly"]
