[package]
name = "asset_loading"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
application = { path = "../application" }
asset_model = { path = "../asset_model" }
derive-new = "0.5.6"
heck = "0.3.1"
itertools = "0.8.0"
log = "0.4.6"
map_model = { path = "../map_model" }
object_type = { path = "../object_type" }
serde = "1.0.94"
strum = "0.15.0"
toml = "0.5.1"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
derive_deref = "1.1.0"
hamcrest = "0.1.5"
pretty_assertions = "0.6.1"
tempfile = "3.1.0"

[features]
nightly = ["amethyst/nightly"]
