[package]
name = "character_loading"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
character_model = { path = "../character_model" }
charge_model = { path = "../charge_model" }
derivative = "1.0.2"
derive-new = "0.5.6"
derive_deref = "1.1.0"
game_input_model = { path = "../game_input_model" }
lazy_static = "1.3.0"
object_loading = { path = "../object_loading" }
object_model = { path = "../object_model" }
sequence_model = { path = "../sequence_model" }
toml = "0.5.1"
typename = "0.1.1"
typename_derive = "0.1.3"

[dev-dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "test-support", "vulkan"] }
amethyst_test = { git = "https://github.com/amethyst/amethyst.git" }
application = { path = "../application" }
pretty_assertions = "0.6.1"
sequence_loading = { path = "../sequence_loading" }

[features]
nightly = ["amethyst/nightly"]
