[package]
name = "ui_model"
version = "0.17.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["no-slow-safety-checks", "vulkan"] }
asset_derive = { path = "../asset_derive" }
asset_model = { path = "../asset_model" }
application_menu = { path = "../application_menu" }
character_selection_ui_model = { path = "../character_selection_ui_model" }
control_settings_model = { path = "../control_settings_model" }
derivative = "1.0.3"
derive-new = "0.5.8"
input_reaction_model = { path = "../input_reaction_model" }
map_selection_ui_model = { path = "../map_selection_ui_model" }
sequence_model = { path = "../sequence_model" }
serde = { version = "1.0.104", features = ["derive"] }
slotmap = { version = "0.4.0", features = ["serde"] }
sprite_model = { path = "../sprite_model" }
strum = "0.17.1"
strum_macros = "0.17.1"
ui_button_model = { path = "../ui_button_model" }
ui_menu_item_model = { path = "../ui_menu_item_model" }
