[package]
name = "assets_built_in"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[dependencies]
asset_model = { path = "../asset_model" }
lazy_static = "1.3.0"
map_model = { path = "../map_model" }
