[package]
name = "numeric_newtype_derive"
version = "0.18.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true
doctest = false
test = false

[dependencies]
proc-macro2 = "1.0.10"
proc_macro_roids = "0.7.0"
quote = "1.0.3"
syn = { version = "1.0.17", features = ["extra-traits", "visit"] }

[dev-dependencies]
derive_more = "0.99.5"
