[package]
name = "numeric_newtype_derive"
version = "0.13.0"
authors = ["Azriel Hoh <mail@azriel.im>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
proc_macro_roids = "0.4.0"
quote = "1.0.2"
syn = { version = "1.0.3", features = ["extra-traits", "visit"] }

[dev-dependencies]
derive_more = "0.15.0"
